# -*- coding: utf-8 -*-
"""generate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UOKAsADalqAq47AbFCWkA1RmAW9wUjGd
"""

import cgi
form = cgi.FieldStorage()
ingredient =  form.getvalue('searchbox')

print(ingredient)

